### ISSUE TITLE
이미지 슬라이더 z-index 에러

### ISSUE THREAD

**Issue by HoisubLee** [Hanhae99-final-3team/final_FE#102]
#93 에서 이미지 슬라이더 css 변경하신 것 확인했습니다.
하지만 게시글 등록하기랑 겹쳐지는 이슈가 있네용..

![image](https://user-images.githubusercontent.com/89531122/190287584-7cacc9a1-da28-4286-81b7-8eb31ecd3bca.png)
괜찮으신 시간에 수정 부탁드려요!

**Comment by crystal993** [comment]
# #104 이미지 슬라이더 이슈 해결 

이미지 슬라이더 이슈 해결했습니다!  하단의 fix button에 z-index를 더 높여줬습니다.
