### ISSUE TITLE
[UI/UX] 채팅방 디자인 완료, 가격비교 수정

### ISSUE THREAD

**Issue by thisLife-hyeon** [Hanhae99-final-3team/final_FE#123]
[채팅]
- 채팅방 디자인 완료.

[가격 비교 아코디언 수정사항]
- 가격 비교 → 가격 비교하기
- 폰트 16px, medium → 14px, bold
- border 1px → 2px

[alert 창]
- 공통 디자인 80% 작업.
- 레이어 팝업(모달) 형태

[alert 발생화면]
- 비로그인 상태에서 글쓰기 버튼 클릭
- 비로그인 상태에서 게시글 페이지내 찜버튼 클릭
- 게시글 작성중 뒤로가기 클릭
- 게시글 삭제 버튼 클릭
- 회원가입 중복확인 바튼 클릭

**Comment by thisLife-hyeon** [comment]
[논의 요구사항]
GNB바탕색과 중요 버튼 색상이 똑같다 보니,
버튼 중요도가 떨어져보이는 것 같습니다.
맨 처음 시안처럼 흰바탕에 보라색아이콘으로 변경하는 것은 어떨까요?

**Comment by crystal993** [comment]
앗 버튼 중요도도 중요한데, 흰색 바탕이면 너무 밋밋할 것 같다는 생각이 드네요...ㅜㅠ

**Comment by crystal993** [comment]
저는 좋습니다! 다른 분들도 괜찮으시다면 내일 오후나 주말 중으로 빠르게 바꿔보겠습니다!
