### ISSUE TITLE
[UI/UX] PC버전 가이드 작업중

### ISSUE THREAD

**Issue by thisLife-hyeon** [Hanhae99-final-3team/final_FE#141]
![image](https://user-images.githubusercontent.com/90155180/191163392-b43d3dcc-7e86-4e84-add3-938e62e5173d.png)
page에서 PC선택하시면 볼 수 있습니다!

**[PC버전 디자인 안내사항]**
- break point : 1280px
- 와이어 프레임상 대지 사이즈 1440px, 내부 콘텐츠 영역 1276px로 가이드 잡았습니다!
- 해상도가 늘어나더라도 1276px 넘어가는 여백 부분만 늘어나는 방식으로 작업 부탁드립니다!
- 
* 이 내용 이외에는 대강 가이드라고 생각해주세요..!
* 반응형이다보니 ,레이아웃에 초점을 맞춰 빠르게 작업중이라 개체 간 간격 사이즈는 디테일하게 잡지 않았습니다

**Comment by crystal993** [comment]
명현님 깃허브 이슈 발행했었네요  ㅜㅠ 방금 확인했습니다! 넵 감사합니다
