### ISSUE TITLE
메인 슬라이드 영역에는 어떤 광고를 넣으면 좋을지 의논하면 좋을 것 같아요

### ISSUE THREAD

**Issue by crystal993** [Hanhae99-final-3team/final_FE#148]
![image](https://user-images.githubusercontent.com/72599761/191506145-8d06315b-b160-4946-8bad-fb4daa27ca9d.png)

명현님이 와이어프레임으로 메인에 이미지 슬라이더 부분 작업해주셨습니다! 
마케팅 특강 듣고 금요일에 다같이 회의할 때 
이 안에 어떤 내용 들어가면 좋을지 의논하면 좋을 것 같습니다 ㅎㅎ

**Comment by HoisubLee** [comment]
피그마를 확인해보니

상단에 슬라이드 형식 배너
1. 설명배너
2 ~. 광고배너

로 적어두셨는데, 설명배너는 확정인 것 같고(너무 좋네요!)

광고 배너에 어떤 것이 들어가면 좋을지 의논하면 좋겠다는 말씀이신거죠??

**Comment by crystal993** [comment]
넵 맞습니다!

**Comment by HoisubLee** [comment]
저한테는 저 광고의 의미가 두 가지로 해석되는데요
1. 우리 사이트에 대한 이벤트 광고 배너
2. 다른 사이트나 상품에 대한 광고 배너

이렇게 해석되는데 둘 다 포함인건지 궁금합니당ㅎㅎ
1번이라면 설문조사 구글form이랑 연결되는 배너 있었으면 좋겠네요!
상세한 것은 더 고민하고 금요일 회의까지 준비해보겠습니당!
