### ISSUE TITLE
카테고리 버튼 관련 의견드립니다.

### ISSUE THREAD

**Issue by fabius96** [Hanhae99-final-3team/final_FE#154]
<img width="371" alt="image" src="https://user-images.githubusercontent.com/108924263/191871377-ccde4915-50e2-4fec-8010-9f11a95f35ad.png">
현재 카테고리에 의한 분류를 사용할 경우 카테고리가 선택되었는지에 대한 확인(선택한 카테고리의 색이 변한다던가)이 불가하며 취소 또한 불가하여 개발자 도구에 들어가서 해당 카테고리에 대한 값을 세션에서 삭제해주어야합니다.
본격적으로 마케팅을 진행하기 전에 이 부분에 대한 해결이 필요하다는 생각이 드는데 혹시 수정님의 생각은 어떠신가요?

**Comment by crystal993** [comment]
저도 이 부분은 마케팅 시작전에 해결해야한다고 생각합니다!
