### ISSUE TITLE
로그인/회원가입 폼/모달 변경

### ISSUE THREAD

**Issue by crystal993** [Hanhae99-final-3team/final_FE#162]
- [x] 로그인 폼 css 
- [x] 회원가입 폼 css 
- [x] 모달 css 
- [x] 메인 select css
- [x] 댓글 css
- [x] 댓글 수정 기능 API 연결
- [x] 댓글 개별 수정 기능
- [x] 토글 체크박스 버튼 보이는 에러 css - 숨기기 
- [x] 로그인폼 경고 문구 
- [x] 카테고리 localStorage 값 시간 지나면 임시로 지우기
- [x] 이미지 슬라이더 반응형으로 이미지 넣기 
- [x] 메인 화면 멍냥마켓 카테고리누르면 카테고리명으로 바꾸기
- [x] 카카오톡 공유할 때 og이미지 변경
- [x] 카카오톡 devloper 로고로 변경
- [x] 메인 페이지 api url 주소 변경
- [x] 카카오 소셜 로그인
- [x] 설문 배너에 설문조사 링크 넣기
- [x] 댓글 입력창 커서 위치 에러 해결
- [x] 긴 댓글 달 때 프로필 아이콘, 수정,삭제 버튼 비율 깨지는 거 해결하기 
- [x] 검색헤더 input 자동완성 off 하기 
- [x] 설문 배너 날짜 바뀐걸로 수정
- [x] 카테고리 아이콘 교체
- [x] 푸터 문구 바꾸기
- [x] 카카오 로그인 css 
------------------ 모달 -----------------
- [x] 검색 자동저장, 모두지우기 모달 추가
- [x] 메인 채팅 아이콘이 있는 헤더와 채팅하기 버튼 눌렀을 때도 '기능구현 중입니다' 알럿 추가
- [x] 댓글 눌렀을 때 로그인이 필요합니다 모달 띄우기
- [x] 게시글 삭제 모달 
------ 회원가입
- [x] 아이디 중복확인 모달
- [x] 회원가입 아이디 중복확인, 닉네임 중복확인 공백 전송 막기
- [x] 닉네임 중복확인 모달
- [x] 기존에 있는 아이디나 닉네임으로 회원가입시 기존에 있는 회원입니다 모달 처리
- [x] 닉네임 또는 아이디 중복확인 안했을 시 회원가입 버튼 누르면 중복확인 안내 모달 처리

**Comment by crystal993** [comment]
data
: 
{msg: '가입이 가능한 회원입니다.', success: true}

data
: 
{msg: '이미 존재하는 회원입니다.', success: false}

**Comment by HoisubLee** [comment]
댓글 수정 시, id값이 이중으로 전달되는 것으로 보입니다!
![image](https://user-images.githubusercontent.com/89531122/192925238-1dfb5d59-61a5-4ebf-a1e8-0530a31dd029.png)
이 이유때문인지 수정이 안먹히고 있습니당ㅠㅠ
확인부탁드려요~

다 아니네요.. 토큰만료로 인한 이슈로 확인되었습니다!
