### ISSUE TITLE
아이폰환경에서 토글 버튼

### ISSUE THREAD

**Issue by HoisubLee** [Hanhae99-final-3team/final_FE#163]
토글버튼에 체크박스 형태가 보입니다..
해당 문제 해결이 가능할까요?ㅠㅠ
![IMG_7116](https://user-images.githubusercontent.com/89531122/192555941-9abdb5e5-d444-470c-b984-4294c6df4b8a.png)
![IMG_7117](https://user-images.githubusercontent.com/89531122/192555981-ea532687-2be4-4499-874f-6bbe96f41d9e.png)

**Comment by crystal993** [comment]
넵 가능합니다~~~~!

**Comment by crystal993** [comment]
#174

**Comment by HoisubLee** [comment]
![KakaoTalk_20221003_010833524](https://user-images.githubusercontent.com/89531122/193464538-51fa1227-33ea-45bc-8675-b3e933766521.png)
크으~! 해결된 부분 확인했어요! 멋집니당~
