### ISSUE TITLE
[유저피드백 3] 스크롤바가 유지되는 에러 수정

### ISSUE THREAD

**Issue by crystal993** [Hanhae99-final-3team/final_FE#170]
게시글 상세페이지, 작성페이지, 수정페이지, 마이페이지 총 4개의 페이지에서 해당 에러가 발생했습니다. 수정하겠습니다. 

### 에러 고치기 전
![스크롤바에러f](https://user-images.githubusercontent.com/72599761/193451294-cedf984c-be55-42ee-91cd-9335a8ca7550.gif)

**Comment by HoisubLee** [comment]
메인페이지에서 로고 클릭 시, 스크롤 최상위 + 카테고리는 초기화 가능하실까요?

**Comment by crystal993** [comment]
넵 가능합니다!
이 기능이랑은 조금 관련없는 이슈라 
회섭님이 말씀하신 기능을 이슈를 따로 발행했습니다!

**Comment by crystal993** [comment]
### 에러 고친 후
![스크롤바에러고침](https://user-images.githubusercontent.com/72599761/193451289-5d73ede8-c655-488b-83d6-441123a1d2b3.gif)



scrollIntoView 를 도입하게 된 이유입니다. 
scrollTop, toScroll, scrollIntoView 등 상단으로 올리는 방법이 많았고, 차례대로 적용을 했습니다.  
scrollTop, toScroll로 최상단으로 스크롤을 올릴 때 
ref로 감지해야할 대상을 최상단으로 올리지 않아서 잘 동작하지 않은 건데, scrollTop, toScroll을 잘못쓰고 있는줄 알고 다른 방법들을 찾아보느라 헤맸습니다… 🤣 

다른 방법으로 scrollIntoView를 쓰고 있을 때 감지해야할 대상을 최상단에 위치시키는 해결 방법을 떠올리게 되었고,  ref로 감지해야할 대상을 최상단에 두니까 잘 동작했습니다!!! 🎉🎉

useRef로 페이지 최상단에 있는 span태그를 감지해서 스크롤바를 span태그 위치로 올리도록 useEffect훅을 이용해서 구현했습니다. 의존성 배열을 빈 배열로 만든 이유는 페이지에 처음 접속할 때 스크롤바가 페이지 맨 위에 존재하는 span 태그 위치로 이동할 수 있도록 하기 위해서입니다..! 

```jsx
const divRef = useRef();
  useEffect(() => {
    divRef.current.scrollIntoView();
  }, []);

// 페이지 최상단에 ref로 감지하는 span태그 존재.  
<span ref={divRef}></span>
```
### scrollIntoView 
- **특정 요소 위치로 화면 스크롤 이동하기**
- **element기반으로 사용하는거라 특정 element를 기준으로 스크롤을 이동**

에러 해결 완료🎉🎉

**Comment by HoisubLee** [comment]
아쉬움이 남네요ㅠㅠ흑흑..
