### ISSUE TITLE
[UI/UX] 게시글 디자인 작업

### ISSUE THREAD

**Issue by thisLife-hyeon** [Hanhae99-final-3team/final_FE#25]
게시글 작성 및 거래완료 게시글 페이지 작업 80% 진행하였습니다.
게시글 완성 후 메인페이지와 메뉴 탭 작업 예정입니다.

**Comment by KoreanCodingMachine** [comment]
혹시 커뮤니티 페이지는 언제쯤 작업 진행되는지 여쭤봐도 괜찮을까요 ?
