### ISSUE TITLE
[UI/UX] 검색 페이지 UI/UX 관련된 의논 사항 

### ISSUE THREAD

**Issue by crystal993** [Hanhae99-final-3team/final_FE#82]
명현님 안녕하세요! 
의논할 사항이 몇가지 있는데, 잊을까봐 이슈 발행합니다!! 
목요일에 민영 튜터님(React 개발자)께 저희 조 와이어프레임을 기반으로 차트 관련하여 피드백 받게 되었습니다. 

## 의논사항 1 - 게시글 상세 페이지 - 가격 차트 
- 게시글 상세 페이지에서 가격 차트가 영역을 굉장히 많이 차지하고 있기 때문에 배치를 바꾸면 좋을 것 같다고 하셨습니다. 
  아코디언 형식으로 개발하긴 하지만, 그래도 차지하는 영역이 굉장히 크다고 피드백 주셨습니다!!! 😂😂😂😂😂😂
  우리 서비스에서 어떤 부분을 사용자들이 제일 먼저 보면 좋을지 생각해보고 배치를 옮기면 좋을 것 같다고 하셨습니다. 

## 의논사항 2 - 검색 페이지 - 자동 저장 토글 위치와 전체 삭제 버튼 
![image](https://user-images.githubusercontent.com/72599761/189484585-1ffbd675-31c0-4659-bc6a-ac44cbbd9a5b.png)
- 현재 토글 위치와 전체 삭제 버튼이 같은 라인에 존재합니다. 
-  저 두 버튼 사이에 공백을 많이 띄운다고 해도 같은 라인에 존재하기 때문에 유저들이 왼쪽은 전체 저장 토글이고, 오른쪽으로 토글을 움직이면 전체 삭제를 하도록 동작한다고 오해할 소지가 있는 것 같습니다. 
- 배치를 다른 라인에 할 건지, 형태를 바꿀 것인지 의논하면 좋을 것 같습니다. 

## 의논사항 3 - 검색 페이지 - 최근 검색어 기능 로그인 안했을 때 
최근 검색어는 로그인이 되었을 때만 사용이 가능합니다. 로그인 안했을 때 최근 검색어에 대한 섹션을 안 보이게 처리하는 것이
좋은지, 아니면 버튼들은 다 그대로 놔두고 모달로 서비스 이용을 유도할 건지 의논하면 좋을 듯 합니다. 

## 의논사항 4 - 검색 결과 페이지 - 검색 결과에 대한 메세지?? 
![image](https://user-images.githubusercontent.com/72599761/189484567-e06d250e-69aa-4ed9-bce9-1cad6020d167.png)
현재 와이어 프레임을 보면 검색 결과에 위치가 뜹니다. 
위치가 아닌 '키워드'에 대한 검색 결과 이런식으로 문구가 뜨는 게 사용자 입장에서 좋을 것 같다는 생각이 듭니다. 
명현님 생각은 어떠신지 의견이 궁금합니다! 이것도 같이 의논하면 좋을 것 같습니다.

## 의논사항 5 검색 결과 페이지 - 검색 결과가 없을 때 
![image](https://user-images.githubusercontent.com/72599761/189485033-fef2abfe-ad15-499e-a7cc-33095a548753.png)

현재 저희 서비스는 검색 결과가 없을 때 빈 화면이 나옵니다.  😂
밑에 구글 사진 처럼 검색 결과가 없습니다. 문구를 쓰면 좋을 것 같은데 이것도 의논하면 좋을 것 같습니다. 
![image](https://user-images.githubusercontent.com/72599761/189484850-2099f60a-894b-4bdc-a447-a77b2b9c18f7.png)

## 의논사항 6 - 메인 페이지 
메인 페이지에 서비스에 대한 설명이 슬라이더로라도 존재하면 좋을 것 같은데 명현님 의견이 궁금합니다. 이것도 의논하면 좋을 것 같습니다! 

더 생기면 추가하겠습니다! 
추석 연휴 잘 보내세요~~ 😃

**Comment by thisLife-hyeon** [comment]
1. 댓글 위로 위치 변경 (아코디언형식 유지는 논의)

2. 자동저장 끄기(텍스트&밑줄) 형식으로 처리하는 방식으로 변경 or 자동저장 위치를 하단으로 변경

3. 최근검색어 키워드 부분에 '로그인이 필요한 기능입니다' 형식의 문구 노출.
 3-1 : 섹션을 아예 없애버리면 기능이 아예 없다고 생각할 수 있을 것 같습니다. (열심히 만들었는데ㅠㅠ)
 3-2 : 모달사용은 사용성 저하가 우려됩니다..!

4. 원래는 검색gnb input부분에 넣으려고 했었습니다! (수정을 안했네요..ㅎㅎ) 이 부분은 논의가 필요할 것 같습니다~
 4-1. 검색gnb input에 넣으면 고정되어 있기 때문에 스크롤 후에도 알 수 있다는 장점 / 4-2보다는 텍스트가 작아 사이트가 익숙하지 않은 사람들은 검색 후 맞게 검색했는지 못찾을 수도 있을 것 같음
 4-2. 말씀 주신대로 타이틀에 넣으면 텍스트가 커서 한눈에 알아볼 수 있다는 장점 / 스크롤시 안보이기 때문에 검색한 내용을 까먹을 수 있음

5. 검색결과 없음 페이지 추가.

6. 홈화면에 광고배너를 만들고 싶었으나 딱히 광고할게 없어 고민하다 없애버렸는데, 첫번째에 멍냥마켓 소개배너를 넣으면 좋을 것 같네요~ 저도 찬성입니다!!

**Comment by crystal993** [comment]
1. 내일 오시면 의논하면 좋을 것 같습니다! 
2. 자동 저장 끄기 켜기 토글을 열심히 만들어서 없애면 너무 아쉬울 것 같습니다 ㅜ 위치를 하단으로 변경하는건 어떠신가용
3. 명현님이 제안해주신 문구 노출 좋습니다!!  
4.  4-1과 4-2 같이 하는 건 어떠신가요?? 
5. 페이지 추가 안해도 문구만 조건에 따라 바꾸는 거 가능할 것 같습니다! 
6. 저도 찬성입니다!!! 😁😀😄😍🥰
