### ISSUE TITLE
[UI/UX] 찜 페이지 관련한 의논사항 

### ISSUE THREAD

**Issue by crystal993** [Hanhae99-final-3team/final_FE#88]
명현님 안녕하세요! 
찜 페이지에서 요청드릴 것과 의논사항이 있어서 이슈 발행합니다! 

## 의논사항 1 
![image](https://user-images.githubusercontent.com/72599761/189563189-1e5258f0-40c4-4c19-923d-51ef77b08c9a.png)
![image](https://user-images.githubusercontent.com/72599761/189563202-1a1acb54-2a4e-4239-b85a-0fd089efd824.png)
하트 아이콘을 내가 찜한 목록 페이지에서 누르면 찜 취소가 되게 하는 기능을 추가하면 유저 입장에서 더 편리할 것 같다는 
생각이 들었습니다. 명현님 의견은 어떠신가요??

**Comment by crystal993** [comment]
하트 아이콘에 흰색 라인을 넣는 게 잘 안됩니다! 방법을 찾아보긴 하겠지만 혹시 모르니 와이어프레임에 있는 흰색 아이콘도 svg파일로 주실 수 있으실까요?? 

![image](https://user-images.githubusercontent.com/72599761/189563417-9af19718-3d01-4055-9be4-53ca9759bbc1.png)

**Comment by thisLife-hyeon** [comment]
Pc의 경우 hover에서 인터랙션을 주어 누르면 해제가 된다~ 라는 것을 예상가능하게 할 수 있지만, 모바일에서는 다음 동작을 예상할 수 없어 당황할 수 있을 것 같습니다..!
찜 취소가 되는순간 찜목록에서 바로 사라지는 구조라면 더더욱 조심해야할 것 같아요ㅠ 실수로 눌렀는데 사라져버리면 사용자 입장에서 당황스러울 수 있으니까요ㅠㅠ!

넵!! 아이콘 오후에 보내드리겠습니다:)

**Comment by crystal993** [comment]
앗 그렇군요!! 그러면 그 기능은 개발하지 않는 게 좋겠네요! 저는 있으면 좋을 것 같다고 생각했는데, 명현님 얘기 듣고 보니깐 유저 입장에서는 당황스러울 수 있겠군요!

**Comment by crystal993** [comment]
명현님이 말씀해주신 거 전부 반영했습니다~
